user:
    path:     /
    defaults: { _controller: "CEUserBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "CEUserBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "CEUserBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "CEUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "CEUserBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "CEUserBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "CEUserBundle:User:delete" }
    requirements: { _method: post|delete }

